---
version: "3.7"

networks:
  haproxy:

services:
  haproxy:
    image: haproxy:1.9-alpine
    ports:
      - "443:443"
      - "80:80"
    read_only: true
    stdin_open: false
    tty: false
    volumes:
      - type: "bind"
        source: "./config/haproxy.cfg"
        target: "/usr/local/etc/haproxy/haproxy.cfg"
    networks:
      - haproxy
